#dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: test
ribbon:
    ServerListRefreshInterval: 5000
Aslog:
  serviceUrl: http://LOGSERVICE
  mname: create
  types: Debug, Info, Warn, Error
  serviceId: logcenter
#系统健康检测