#dev
zuul:
  routes:
    usercenter:
      path: /uc/**
      serviceId: usercenter
    usercenter-url:
      path: /uc-url/**
      url: http://localhost:1234
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
