#dev
#
#    usercenter:
#      path: /uc/**
#     serviceId: usercenter
#    usercenter-url:
#      path: /uc-url/**
#      url: http://localhost:1234
#
zuul:
  routes:
    SYSTEMCENTER:
      path: /sc/**
      serviceId: SYSTEMCENTER
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
