#dev
#
#    usercenter:
#      path: /uc/**
#     serviceId: usercenter
#    usercenter-url:
#      path: /uc-url/**
#      url: http://localhost:1234
#
zuul:
  routes:
    sc:
      path: /sc/**
      serviceId: systemcenter
      stripPrefix: false
    uc:
       path: /uc/**
       serviceId: usercenter
       stripPrefix: false
    log:
       path: /log/**
       serviceId: logcenter
       stripPrefix: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
