#dev
#
#    usercenter:
#      path: /uc/**
#     serviceId: usercenter
#    usercenter-url:
#      path: /uc-url/**
#      url: http://localhost:1234
#
zuul:
  routes:
    sc:
      path: /sc/**
      serviceId: systemcenter
      stripPrefix: false
    uc:
       path: /uc/**
       serviceId: usercenter
       stripPrefix: false
security:
    user:
    password: user
    ignored: /
    sessions: never
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
