#dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: test
#系统健康检测
management:
  port: 9528 # Set Security Port
  security:
    enabled: false
  health:
    mail:
      enabled: false # health except mail
security:
  user:
    name: g
    password: sisi